{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.751.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"New_Data\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "MeasuresTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5b53602045b3488ab3a2d90557f45bf3"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "08cbecd2-fe43-4b89-9447-f2428a09d1d1",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "016f70e8-5fd2-46da-ab89-c4e0c1e09053",
        "measures": [
          {
            "name": "MDTotal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[MD])",
            "lineageTag": "8a20c45b-7774-4fa9-911d-820277a91d53"
          },
          {
            "name": "NurseTotal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Nurse])",
            "lineageTag": "267985c0-e691-4fa6-b304-10f8c1d431cc"
          },
          {
            "name": "AdminBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Admin > 3 days])",
            "lineageTag": "aa44a205-9d7a-48a2-880c-48025572aa29"
          },
          {
            "name": "MDBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[MD > 3 days])",
            "lineageTag": "d1af0be4-d75b-46be-9414-57c412e3dedb"
          },
          {
            "name": "NurseBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Nurse >3Days])",
            "lineageTag": "741b7b08-9026-4bd4-ae79-42fa3262530a"
          },
          {
            "name": "TotalBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Total >3 Days])",
            "lineageTag": "1d73b596-53e4-41ca-abaa-539ee883f01c"
          },
          {
            "name": "AdminPercentageBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[% >3 Admin])",
            "lineageTag": "85bafddf-e9c8-4255-bffb-995c01be5624"
          },
          {
            "name": "AdminTotal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Admin])",
            "lineageTag": "e75f1aa0-7de2-43cf-9313-122e1465447f"
          },
          {
            "name": "MDPercentageBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[% >3 MD])",
            "lineageTag": "d5d57ae5-8349-47b3-9f26-4d67c0abd22c"
          },
          {
            "name": "NursePercentageBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[%>3 Nurse])",
            "lineageTag": "e493a60a-c799-42e2-ae7c-74f7c14e78dd"
          },
          {
            "name": "Todays_Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total], New_Data[Date] = MAX(New_Data[Date]))",
            "lineageTag": "a85e5004-6b14-4ef4-8339-41eeff7ce01c"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[Total Numbers])",
            "lineageTag": "a740e274-6e55-4108-add9-3459efabf5cc"
          },
          {
            "name": "TotalPercentageBacklog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(New_Data[%>3Days])",
            "lineageTag": "b03440c9-46de-4db8-816d-1ed0a9d45927"
          },
          {
            "name": "Todays_Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([TotalPercentageBacklog], New_Data[Date] = MAX(New_Data[Date]))",
            "lineageTag": "b9c96080-ae69-4c0d-892f-90c367138ba0"
          },
          {
            "name": "Todays_Backlog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([TotalBacklog], New_Data[Date] = MAX(New_Data[Date]))",
            "lineageTag": "7ad3ed87-29ac-4175-a98b-286ed49a16ec"
          }
        ],
        "partitions": [
          {
            "name": "MeasuresTable",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "New_Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f94c6fe3-3db9-4c89-9705-43227b6c2dbe",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Nurse >3Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc817ba2-cfa2-45ec-9236-f242d77cc3a2",
            "sourceColumn": "Nurse >3Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Nurse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d36a9d9c-81d0-4ea8-99a7-d65f393c3786",
            "sourceColumn": "Nurse",
            "summarizeBy": "sum"
          },
          {
            "name": "%>3 Nurse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b352ae7a-1f76-4a39-af47-0298741cc0df",
            "sourceColumn": "%>3 Nurse",
            "summarizeBy": "sum"
          },
          {
            "name": "MD > 3 days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68f55ed0-0c2b-47d4-910a-8c32d8af00bf",
            "sourceColumn": "MD > 3 days",
            "summarizeBy": "sum"
          },
          {
            "name": "MD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0054df8-6df9-4b1b-ad83-28188b6471ef",
            "sourceColumn": "MD",
            "summarizeBy": "sum"
          },
          {
            "name": "% >3 MD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2dacf040-2328-40ba-b0e7-3468ab84e282",
            "sourceColumn": "% >3 MD",
            "summarizeBy": "sum"
          },
          {
            "name": "Admin > 3 days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16867f40-66aa-4970-b5ca-98336416446d",
            "sourceColumn": "Admin > 3 days",
            "summarizeBy": "sum"
          },
          {
            "name": "Admin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "57d34117-65e0-4bc4-b00e-28ca702f14d8",
            "sourceColumn": "Admin",
            "summarizeBy": "sum"
          },
          {
            "name": "% >3 Admin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec0d7319-1ef4-4f7f-874a-5390b943127a",
            "sourceColumn": "% >3 Admin",
            "summarizeBy": "sum"
          },
          {
            "name": "Total >3 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2fe8018-8b5c-4a14-a367-5005eea7fa67",
            "sourceColumn": "Total >3 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Numbers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81fd72d5-80dd-4ee3-8102-1fab6bcbe9a4",
            "sourceColumn": "Total Numbers",
            "summarizeBy": "sum"
          },
          {
            "name": "%>3Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c003913-081d-49bf-a104-fd61e862dbcc",
            "sourceColumn": "%>3Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Oldest Date ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c13f6330-50c2-4258-8ad0-dd0bf1f7a36c",
            "sourceColumn": "Oldest Date ",
            "summarizeBy": "none"
          },
          {
            "name": "Comment ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af58b03b-ff00-4eda-9ade-93869ea55982",
            "sourceColumn": "Comment ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aacb3ca0-b545-40d0-aed2-7df9c9d647e2",
        "partitions": [
          {
            "name": "New_Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://dvagov.sharepoint.com/sites/V19BOSSLeadership-WeeklyOversightReviewNumbers/\", [ApiVersion = 15]),",
                "    #\"Denver Daily RFS Numbers xlsx_https://dvagov sharepoint com/sites/V19BOSSLeadership-WeeklyOversightReviewNumbers/Shared Documents/Weekly V19 Oversight Review Meeting Numbers/Denver Daily RFS/\" = Source{[Name=\"Denver Daily RFS Numbers.xlsx\",#\"Folder Path\"=\"https://dvagov.sharepoint.com/sites/V19BOSSLeadership-WeeklyOversightReviewNumbers/Shared Documents/Weekly V19 Oversight Review Meeting Numbers/Denver Daily RFS/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Denver Daily RFS Numbers xlsx_https://dvagov sharepoint com/sites/V19BOSSLeadership-WeeklyOversightReviewNumbers/Shared Documents/Weekly V19 Oversight Review Meeting Numbers/Denver Daily RFS/\"),",
                "    Table1_Table = #\"Imported Excel Workbook\"{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(Table1_Table, {\"%>3 Nurse\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Errors\",{{\"Date\", Order.Descending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}